#!/bin/bash
echo "=========================================="
echo "Municipal Intel - Deployment Guide"
echo "=========================================="
echo ""
echo "This app is deployed on Railway.app"
echo ""
echo "Current deployment:"
echo "  URL: https://web-production-a13f5.up.railway.app"
echo "  Domain: govtechdiagnostic.com (pending DNS)"
echo ""
echo "=========================================="
echo "To Deploy Updates:"
echo "=========================================="
echo ""
echo "1. Commit your changes:"
echo "   git add ."
echo "   git commit -m 'Your update message'"
echo "   git push origin main"
echo ""
echo "2. Railway auto-deploys from main branch"
echo "   View deployment: https://railway.app"
echo ""
echo "=========================================="
echo "Environment Variables (Railway):"
echo "=========================================="
echo ""
echo "Required:"
echo "  DATABASE_URL        - Neon Postgres connection string"
echo "  JWT_SECRET_KEY      - Random secure key for sessions"
echo "  RESEND_API_KEY      - Resend API key for magic links"
echo "  RESEND_FROM_EMAIL   - Municipal Intel <noreply@govtechdiagnostic.com>"
echo "  APP_URL             - https://govtechdiagnostic.com"
echo ""
echo "Optional:"
echo "  ANTHROPIC_API_KEY   - Claude API for AI-enhanced analysis"
echo ""
echo "=========================================="
