#!/bin/bash
echo "=========================================="
echo "Municipal Intel - Manual Deployment Guide"
echo "=========================================="
echo ""
echo "Since Streamlit Cloud web interface isn't working,"
echo "here's what to check:"
echo ""
echo "1. Verify you're signed in to GitHub:"
echo "   https://github.com"
echo ""
echo "2. Make sure you have a Streamlit Cloud account:"
echo "   - Sign up at: https://share.streamlit.io"
echo "   - Use your GitHub account (jacobmr212)"
echo ""
echo "3. Your repo is ready at:"
echo "   https://github.com/jacobmr212/municipal-intel"
echo ""
echo "4. Try the direct link again:"
echo "   https://share.streamlit.io/deploy?repository=jacobmr212/municipal-intel&branch=main&mainModule=app.py"
echo ""
echo "=========================================="
echo "OR - Deploy to Alternative Platforms:"
echo "=========================================="
echo ""
echo "Option A: Hugging Face Spaces (Free)"
echo "  - Go to: https://huggingface.co/spaces"
echo "  - Create new Space"
echo "  - Select: Streamlit SDK"
echo "  - Connect your GitHub repo"
echo ""
echo "Option B: Railway (Free tier)"
echo "  - Go to: https://railway.app"
echo "  - Deploy from GitHub"
echo "  - Select: jacobmr212/municipal-intel"
echo ""
echo "=========================================="
